# Model Specification
model:
  name: HEDUNet
  classes: 2        # Anzahl der Segmentation-Klassen (z. B. Eis / Hintergrund)
  in_channels: 2    # Anzahl der Eingabekanäle (z. B. HH/VV oder RGB)
  args:
    input_channels: [1, 2]
    base_channels: 8
    stack_height: 5
    merging: attention
    batch_norm: true

# Training Parameters
training:
  feature_pyramid: true
  loss_function: AutoBCE
  batch_size: 32   # Shelf-Bench erwartet training.batch_size
  learning_rate: 0.0001
  epochs: 15
  optimizer: Adam
  scheduler: CosineAnnealingWarmRestarts   # optional, falls gewünscht
  num_workers: 4

# Data Configuration
data:
  parent_dir: ./data   # Hauptpfad für Shelf-Bench
  threads: 4
  train:
    folders:
      - train
    augment: true
    shuffle: true
    batch_size: 32
    num_workers: 4

  val:
    folders:
      - val
    augment: false
    shuffle: false
    batch_size: 32
    num_workers: 4

  # test:
  #   folders:
  #     - test
  #   augment: false
  #   shuffle: false
  #   batch_size: 4
  #   num_workers: 4

# Visualization
visualization:
  tiles:
    - val/images/ERS_20100520_VV_142439_90.pt
    - val/images/ERS_20100520_VV_142439_19.pt
    - val/images/ERS_19941202_VV_222139_5.pt
    - val/images/ERS_19990219_VV_143256_18.pt
