#base configuration

defaults:
  - _self_
  - hydra: default
  - override hydra/launcher: slurm

paths:
  root_local: "/dss/dsstbyfs02/pn49ci/pn49ci-dss-0000/Antartic_Database/git-project/shelf-bench-hedunet/shelfbench-hedunet"
  root_gws: "/dss/dsstbyfs02/pn49ci/pn49ci-dss-0000/Antartic_Database" 

# Main configuration
seed: 0
name: "ice_bench_seg"
save_dir: "/dss/dsstbyfs02/pn49ci/pn49ci-dss-0000/Antartic_Database/git-project/shelf-bench-hedunet/model_outputs/"
data_root: "/dss/dsstbyfs02/pn49ci/pn49ci-dss-0000/Antartic_Database/data/Shelf-Bench/Shelf-Bench-tiles-png"
load_path: true
use_wandb: true
class_names: ["Ocean", "Ice"]
log_freq: 200
save_freq: 1
num_workers: 4
device: "cuda"

model:
  name: "HEDUNet"
  in_channels: 1         # weil IceDataset Graustufen-PNG liefert
  classes: 2             # Ocean vs. Ice
  img_size: 256
  args:
    input_channels: 1
    output_channels: 2
    base_channels: 16
    stack_height: 5
    deep_supervision: true
    merging: "attention"
    batch_norm: true

training:
  batch_size: 16          # evtl. kleiner als 32, je nach GPU-Speicher
  learning_rate: 1e-4
  weight_decay: 1e-4
  epochs: 20
  loss_function: "HEDUNetLoss"
  optimizer: "Adam"
  log_interval: 100
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  mixed_precision: true

data:
  img_size: 256
  augmentation_prob: 0.5
  parent_dir: "/dss/dsstbyfs02/pn49ci/pn49ci-dss-0000/Antartic_Database/data/Shelf-Bench/Shelf-Bench-tiles-png/"